"""Beam map HTML report generation."""

from __future__ import annotations

import base64
import io
from pathlib import Path
from typing import Any

import numpy as np

from opensatcom.payload.beammap import BeamMap


def render_beammap_report(
    beam_map: BeamMap,
    config: dict[str, Any],
    output_path: str | Path,
    plots_dir: str | Path | None = None,
) -> Path:
    """Generate standalone HTML report for a beam map / capacity analysis.

    Includes:
    1. Per-beam summary table (beam_id, points served, mean SINR, mean margin)
    2. SINR heatmap (scatter over az/el grid)
    3. C/(N+I) heatmap
    """
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    output_path = Path(output_path)

    df = beam_map.to_dataframe()
    summary = beam_map.per_beam_summary()

    # Per-beam summary table
    beam_rows = ""
    for bid, stats in sorted(summary.items()):
        beam_rows += (
            f"<tr><td>{bid}</td>"
            f"<td>{stats['points_served']:.0f}</td>"
            f"<td>{stats['sinr_db_mean']:.2f}</td>"
            f"<td>{stats['margin_db_mean']:.2f}</td></tr>\n"
        )

    # Plots
    plots_html = ""

    # SINR scatter/heatmap
    fig, ax = plt.subplots(figsize=(8, 6))
    sinr_vals = df["sinr_db"].replace([np.inf, -np.inf], np.nan)
    sc = ax.scatter(
        df["az_deg"], df["el_deg"],
        c=sinr_vals, cmap="RdYlGn", s=80, edgecolors="k", linewidth=0.5,
    )
    fig.colorbar(sc, ax=ax, label="SINR (dB)")
    ax.set_xlabel("Azimuth (deg)")
    ax.set_ylabel("Elevation (deg)")
    ax.set_title("SINR Map")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=100)
    if plots_dir:
        plots_dir = Path(plots_dir)
        plots_dir.mkdir(parents=True, exist_ok=True)
        fig.savefig(plots_dir / "sinr_map.png", dpi=100)
    plt.close(fig)
    sinr_b64 = base64.b64encode(buf.getvalue()).decode()
    plots_html += f'<img src="data:image/png;base64,{sinr_b64}" alt="SINR Map">\n'

    # C/(N+I) scatter/heatmap
    fig, ax = plt.subplots(figsize=(8, 6))
    sc = ax.scatter(
        df["az_deg"], df["el_deg"],
        c=df["cnir_db"], cmap="RdYlGn", s=80, edgecolors="k", linewidth=0.5,
    )
    fig.colorbar(sc, ax=ax, label="C/(N+I) (dB)")
    ax.set_xlabel("Azimuth (deg)")
    ax.set_ylabel("Elevation (deg)")
    ax.set_title("C/(N+I) Map")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=100)
    if plots_dir:
        fig.savefig(plots_dir / "cnir_map.png", dpi=100)
    plt.close(fig)
    cnir_b64 = base64.b64encode(buf.getvalue()).decode()
    plots_html += f'<img src="data:image/png;base64,{cnir_b64}" alt="C/(N+I) Map">\n'

    # Optional Plotly interactive beam map
    plotly_html = ""
    try:
        from opensatcom.viz.heatmaps import plot_beam_map_interactive

        fig_bm = plot_beam_map_interactive(df, metric="sinr_db")
        plotly_html += '<h2>Interactive Maps</h2>\n'
        plotly_html += fig_bm.to_html(include_plotlyjs="cdn", full_html=False)  # type: ignore[union-attr]
    except ImportError:
        pass  # plotly not installed

    # Overall stats
    mean_sinr = beam_map.sinr_db_mean
    mean_margin = beam_map.margin_db_mean
    margin_color = "#2e7d32" if mean_margin >= 0 else "#c62828"

    html = f"""<!DOCTYPE html>
<html>
<head>
<title>OpenSatCom Beam Map Report</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       max-width: 900px; margin: 40px auto; padding: 0 20px; color: #333; }}
h1 {{ color: #1565c0; }}
table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
th {{ background: #f5f5f5; }}
img {{ max-width: 100%; margin: 10px 0; }}
.margin {{ font-size: 1.4em; font-weight: bold; color: {margin_color}; }}
.footer {{ margin-top: 40px; font-size: 0.85em; color: #888; }}
</style>
</head>
<body>
<h1>Beam Map Report</h1>
<p class="margin">Mean Margin: {mean_margin:.2f} dB | Mean SINR: {mean_sinr:.2f} dB</p>

<h2>Per-Beam Summary</h2>
<table>
<tr><th>Beam ID</th><th>Points Served</th><th>Mean SINR (dB)</th><th>Mean Margin (dB)</th></tr>
{beam_rows}
</table>

<h2>Coverage Maps</h2>
{plots_html}

{plotly_html}

<div class="footer">
Generated by OpenSatCom v0.4.0
</div>
</body>
</html>"""

    output_path.write_text(html)
    return output_path
