"""Mission/time-series HTML report generation."""

from __future__ import annotations

import base64
import io
from pathlib import Path
from typing import Any

import numpy as np


def render_mission_report(
    summary: dict[str, float],
    times_s: np.ndarray,
    margin_db: np.ndarray,
    elev_deg: np.ndarray,
    outages_mask: np.ndarray,
    config: dict[str, Any],
    output_path: str | Path,
    plots_dir: str | Path | None = None,
) -> Path:
    """Generate standalone HTML report for a mission simulation."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    output_path = Path(output_path)

    # Generate plots
    plots_html = ""

    # Margin vs time
    fig, ax = plt.subplots(figsize=(10, 4))
    valid = ~outages_mask
    ax.plot(times_s[valid], margin_db[valid], "b-", linewidth=1.5, label="Margin")
    if np.any(outages_mask):
        ax.axhspan(-100, 0, alpha=0.1, color="red", label="Outage region")
    ax.axhline(0, color="red", linestyle="--", alpha=0.5)
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Margin (dB)")
    ax.set_title("Link Margin vs Time")
    ax.legend()
    ax.grid(True, alpha=0.3)
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=100)
    if plots_dir:
        plots_dir = Path(plots_dir)
        plots_dir.mkdir(parents=True, exist_ok=True)
        fig.savefig(plots_dir / "margin_vs_time.png", dpi=100)
    plt.close(fig)
    margin_b64 = base64.b64encode(buf.getvalue()).decode()
    plots_html += f'<img src="data:image/png;base64,{margin_b64}" alt="Margin vs Time">\n'

    # Elevation vs time
    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(times_s, elev_deg, "g-", linewidth=1.5)
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Elevation (deg)")
    ax.set_title("Elevation vs Time")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=100)
    if plots_dir:
        fig.savefig(plots_dir / "elevation_vs_time.png", dpi=100)
    plt.close(fig)
    elev_b64 = base64.b64encode(buf.getvalue()).decode()
    plots_html += f'<img src="data:image/png;base64,{elev_b64}" alt="Elevation vs Time">\n'

    # Summary table
    summary_rows = ""
    for key, val in summary.items():
        if "availability" in key:
            summary_rows += f"<tr><td>{key}</td><td>{val:.4f}</td></tr>\n"
        else:
            summary_rows += f"<tr><td>{key}</td><td>{val:.2f}</td></tr>\n"

    avail = summary.get("availability", 0.0)
    avail_color = "#2e7d32" if avail >= 0.99 else "#e65100" if avail >= 0.95 else "#c62828"

    html = f"""<!DOCTYPE html>
<html>
<head>
<title>OpenSatCom Mission Report</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       max-width: 900px; margin: 40px auto; padding: 0 20px; color: #333; }}
h1 {{ color: #1565c0; }}
table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
th {{ background: #f5f5f5; }}
img {{ max-width: 100%; margin: 10px 0; }}
.avail {{ font-size: 1.4em; font-weight: bold; color: {avail_color}; }}
.footer {{ margin-top: 40px; font-size: 0.85em; color: #888; }}
</style>
</head>
<body>
<h1>Mission Simulation Report</h1>
<p class="avail">Availability: {avail:.2%}</p>

<h2>Summary Metrics</h2>
<table>
<tr><th>Metric</th><th>Value</th></tr>
{summary_rows}
</table>

<h2>Time-Series Plots</h2>
{plots_html}

<div class="footer">
Generated by OpenSatCom v0.1.0
</div>
</body>
</html>"""

    output_path.write_text(html)
    return output_path
