"""Snapshot link budget HTML report generation."""

from __future__ import annotations

from pathlib import Path
from typing import Any


def render_snapshot_report(
    breakdown: dict[str, float],
    config: dict[str, Any],
    output_path: str | Path,
) -> Path:
    """Generate standalone HTML report for a snapshot link budget.

    Parameters
    ----------
    breakdown : dict of str to float
        Itemised link budget breakdown (keys are parameter names,
        values in dB or Kelvin).
    config : dict
        Raw config dictionary for metadata display.
    output_path : str or Path
        File path for the generated HTML report.

    Returns
    -------
    Path
        Path to the written HTML file.
    """
    output_path = Path(output_path)

    margin = breakdown.get("margin_db", 0.0)
    margin_color = "#2e7d32" if margin >= 0 else "#c62828"

    rows = ""
    for key, val in breakdown.items():
        if key == "rx_system_temp_k":
            rows += f"<tr><td>{key}</td><td>{val:.1f} K</td></tr>\n"
        else:
            rows += f"<tr><td>{key}</td><td>{val:.2f} dB</td></tr>\n"

    html = f"""<!DOCTYPE html>
<html>
<head>
<title>OpenSatCom Snapshot Link Budget</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       max-width: 800px; margin: 40px auto; padding: 0 20px; color: #333; }}
h1 {{ color: #1565c0; }}
table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
th {{ background: #f5f5f5; }}
.margin {{ font-size: 1.4em; font-weight: bold; color: {margin_color}; }}
.footer {{ margin-top: 40px; font-size: 0.85em; color: #888; }}
</style>
</head>
<body>
<h1>Snapshot Link Budget Report</h1>
<p class="margin">Link Margin: {margin:.2f} dB</p>

<h2>Link Breakdown</h2>
<table>
<tr><th>Parameter</th><th>Value</th></tr>
{rows}
</table>

<div class="footer">
Generated by OpenSatCom v0.1.0
</div>
</body>
</html>"""

    output_path.write_text(html)
    return output_path
